<?php

namespace ContainerN325N71;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CxwTQANService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CxwTQAN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CxwTQAN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnimalsController::create' => ['privates', '.service_locator.tIMOa3t', 'get_ServiceLocator_TIMOa3tService', true],
            'App\\Controller\\AnimalsController::delete' => ['privates', '.service_locator._nKaKmD', 'get_ServiceLocator_NKaKmDService', true],
            'App\\Controller\\AnimalsController::index' => ['privates', '.service_locator.4knjDfm', 'get_ServiceLocator_4knjDfmService', true],
            'App\\Controller\\AnimalsController::show' => ['privates', '.service_locator.4knjDfm', 'get_ServiceLocator_4knjDfmService', true],
            'App\\Controller\\AnimalsController::showByCountry' => ['privates', '.service_locator.7HgipzG', 'get_ServiceLocator_7HgipzGService', true],
            'App\\Controller\\AnimalsController::update' => ['privates', '.service_locator._nKaKmD', 'get_ServiceLocator_NKaKmDService', true],
            'App\\Controller\\AnimalsController::updateCountry' => ['privates', '.service_locator.iPuYJwS', 'get_ServiceLocator_IPuYJwSService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AnimalsController:create' => ['privates', '.service_locator.tIMOa3t', 'get_ServiceLocator_TIMOa3tService', true],
            'App\\Controller\\AnimalsController:delete' => ['privates', '.service_locator._nKaKmD', 'get_ServiceLocator_NKaKmDService', true],
            'App\\Controller\\AnimalsController:index' => ['privates', '.service_locator.4knjDfm', 'get_ServiceLocator_4knjDfmService', true],
            'App\\Controller\\AnimalsController:show' => ['privates', '.service_locator.4knjDfm', 'get_ServiceLocator_4knjDfmService', true],
            'App\\Controller\\AnimalsController:showByCountry' => ['privates', '.service_locator.7HgipzG', 'get_ServiceLocator_7HgipzGService', true],
            'App\\Controller\\AnimalsController:update' => ['privates', '.service_locator._nKaKmD', 'get_ServiceLocator_NKaKmDService', true],
            'App\\Controller\\AnimalsController:updateCountry' => ['privates', '.service_locator.iPuYJwS', 'get_ServiceLocator_IPuYJwSService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AnimalsController::create' => '?',
            'App\\Controller\\AnimalsController::delete' => '?',
            'App\\Controller\\AnimalsController::index' => '?',
            'App\\Controller\\AnimalsController::show' => '?',
            'App\\Controller\\AnimalsController::showByCountry' => '?',
            'App\\Controller\\AnimalsController::update' => '?',
            'App\\Controller\\AnimalsController::updateCountry' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AnimalsController:create' => '?',
            'App\\Controller\\AnimalsController:delete' => '?',
            'App\\Controller\\AnimalsController:index' => '?',
            'App\\Controller\\AnimalsController:show' => '?',
            'App\\Controller\\AnimalsController:showByCountry' => '?',
            'App\\Controller\\AnimalsController:update' => '?',
            'App\\Controller\\AnimalsController:updateCountry' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
