<?php

namespace ContainerN325N71;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NKaKmDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._nKaKmD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._nKaKmD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animalsRepository' => ['privates', 'App\\Repository\\AnimalsRepository', 'getAnimalsRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'animalsRepository' => 'App\\Repository\\AnimalsRepository',
            'entityManager' => '?',
        ]);
    }
}
