<?php

namespace ContainerN325N71;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4knjDfmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4knjDfm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4knjDfm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animalsRepository' => ['privates', 'App\\Repository\\AnimalsRepository', 'getAnimalsRepositoryService', true],
        ], [
            'animalsRepository' => 'App\\Repository\\AnimalsRepository',
        ]);
    }
}
