<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN325N71\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN325N71/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN325N71.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN325N71\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN325N71\App_KernelDevDebugContainer([
    'container.build_hash' => 'N325N71',
    'container.build_id' => '31bc35cb',
    'container.build_time' => 1684760481,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN325N71');
